### PR TITLE
OpenFF POPC & POPE Simulations

### PR DESCRIPTION
**Pull request by PEFrankel**

### CODE REVIEW

**Comment by PEFrankel** [comment]
Sources for the OpenFF parameters:
1. Sage ([Boothroyd et al., 2023](https://pubs.acs.org/doi/10.1021/acs.jctc.3c00039) + [Specific version DOI](https://doi.org/10.5281/zenodo.3473553))
2. OpenFF Toolkit ([Mobley et al., 2018](https://pubs.acs.org/doi/10.1021/acs.jctc.8b00640) + [Specific version DOI](https://doi.org/10.5281/zenodo.597754))
3. OpenFF Interchange ([Specific version DOI](https://doi.org/10.5281/zenodo.8147764))

**Comment by pbuslaev** [comment]
> Sources for the OpenFF parameters:
> 
>     1. Sage ([Boothroyd et al., 2023](https://pubs.acs.org/doi/10.1021/acs.jctc.3c00039) + [Specific version DOI](https://doi.org/10.5281/zenodo.3473553))
> 
>     2. OpenFF Toolkit ([Mobley et al., 2018](https://pubs.acs.org/doi/10.1021/acs.jctc.8b00640) + [Specific version DOI](https://doi.org/10.5281/zenodo.597754))
> 
>     3. OpenFF Interchange ([Specific version DOI](https://doi.org/10.5281/zenodo.8147764))

Could you please also comment on which registry you used for parameterization (amber/openeye)? Also, how did you generate interchange object? For the whole bilayer, or for one lipid? If for one lipid, which structure did you use? If for the whole bilayer, which structure format did you provide as input?

Those details might be quite important, for instance amber and openeye charges would be different, since ambertools and openeye AM1-BCC models differ. Different structure formats might lead to different parameters as well. For instance, smiles generated from pdb are sometimes wrong, since pdb does not include the connectivity.

**Comment by PEFrankel** [comment]
OpenEye AM1-BCC was used and individual POPC/POPE lipids were parameterized from sdf files. This repository covering simulation methods and parameter generation answers these questions: 
https://github.com/PEFrankel/OpenFF_Bilayer

**Comment by pbuslaev** [comment]
> OpenEye AM1-BCC was used and individual POPC/POPE lipids were parameterized from sdf files. This repository covering simulation methods and parameter generation answers these questions: https://github.com/PEFrankel/OpenFF_Bilayer

Great! Thanks for the explanation! @ohsOllila I would say that those details are important to mention in the supporting information, or maybe we can provide the link to github repository

**Comment by PEFrankel** [comment]
Either sounds good. The repository covers almost everything and the simulations should be completely reproducible there. If you have any more questions, let me know.

**Comment by pbuslaev** [comment]
Personally, I would be interested in comparing results to lipids parameterized with amber AM1-BCC charges. But I am not sure if it is necessary for the manuscript

**Comment by PEFrankel** [comment]
Apologies I misspoke. Amber AM1-BCC was used, _not_ OpenEye. The similar naming distracted me. Regardless, testing with different charge methods could be interesting. Do you think testing OpenEye vs Amber AM1-BCC with produce significantly different results?

**Comment by pbuslaev** [comment]
I actually don't know. For small molecules, the performance of open-ff was fine with both charge models, so I maybe don't expect big differences. But I agree that testing with a different charge model could be of interest.

**Comment by ohsOllila** [comment]
> > OpenEye AM1-BCC was used and individual POPC/POPE lipids were parameterized from sdf files. This repository covering simulation methods and parameter generation answers these questions: https://github.com/PEFrankel/OpenFF_Bilayer
> 
> Great! Thanks for the explanation! @ohsOllila I would say that those details are important to mention in the supporting information, or maybe we can provide the link to github repository

We will not include details of individual simulations in the databank paper, that would be too much. However, we can put references to above mentioned papers and repository into the table in SI.

**Pull request merged**
