### PR TITLE
update POPC Drude2023 data

### PR DESCRIPTION
**Pull request by batukav**

### CODE REVIEW

**Review by ohsOllila — CHANGES_REQUESTED** [review]
Please name the order parameter files correctly POPEOrderParameters.dat -> POPCOrderParameters.dat

Please remove all the *dat files, *pnz files, WaterDensity.json and LipidDensity.json files from the repo entries. These files are not (at least for now) included in the databank repo (I am sorry, this is probably not instructed anywhere).

It would be also good to fix the POPE->POPC in the info files.

**Comment by batukav** [comment]
I made new commits that address the above issues

**Review by ohsOllila — CHANGES_REQUESTED** [review]
Thanks. There is one more order parameter file to be renamed in folder: [21e](https://github.com/NMRLipids/Databank/tree/main/Data/Simulations/21e)/[025](https://github.com/NMRLipids/Databank/tree/main/Data/Simulations/21e/025)/[21e0257dc453a389dfecaf1774e46253c23f4f5d](https://github.com/NMRLipids/Databank/tree/main/Data/Simulations/21e/025/21e0257dc453a389dfecaf1774e46253c23f4f5d)/[21e0257dc453a389dfecaf1774e46253c23f4f5d](https://github.com/NMRLipids/Databank/tree/main/Data/Simulations/21e/025/21e0257dc453a389dfecaf1774e46253c23f4f5d/21e0257dc453a389dfecaf1774e46253c23f4f5d)

**Comment by batukav** [comment]
This is now also corrected.

**Pull request merged**
